config/routes.rb
Proto::Application.routes.draw do
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out" 
  get "users/new"
  
  root :to => "sessions#new"
  
  namespace :admin do
    resources :members
    resources :products
    resources :logs, :only => [:index]
  end 
  
  resources :sessions

  resources :members, :only => [:show] do
    resources :registers
    resources :offers
  end
    
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  
  respond_to :html, :json
  
  # GET /members/1/offers
  # Provides a list of the Member's Current Offers
  def index
    @member = Member.find(params[:member_id])
    @products = @member.products
  end
  
  def show
    @product = Product.find(params[:id])
    Log.make(session[:mem_id], {:product => @product.id, :action => :click, :type => :offer})
    respond_with do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  
  end
  
  
  
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_product.html.erb
<li>
	<%= link_to member_offer_path(@member, product)  do %>
		<% if !product.image_url.nil? %>
			<%= image_tag product.image_url(:thumb) %>
		<% end %>
		<h3><%=product.name%></h3>
		<p><%= product.desc %></p>
	<% end %>
</li>

app/views/offers/index.html.erb
<% title "Member Offers" %>

<div data-role="content">
	<h3>Name: <%= @member.name %></h3>
	<p>
		<b>Card:</b>
		<%= @member.card_num %>
	</p>

	<ul data-role  = "listview">
		<%= render :partial => "product", :collection => @products %>
	</ul>
	
	
</div>

app/views/offers/show.html.erb
<% title "Offer Details" %>

<div data-role="content">
	<% if !@product.image_url.nil? %>
		<p>
			<%= image_tag @product.image_url(:thumb) %>
		</p>
	<% end %>

	<p>
		<b>Name:</b>
		<%= @product.name %>
	</p>

	<p>
		<b>Short Description:</b>
		<%= @product.desc %>
	</p>
	
	<div data-role="collapsible" data=collasped="true">
			<h3>Long Description:</h3>
			<p><%= @product.long_desc %></p>
	</div>
	
	


</div>

<%= link_to 'My Offers', member_offers_path(@member), "data-role" => "button", "data-icon" => "back" %>